### ISSUE TITLE
initial concept art

### ISSUE THREAD

**Issue by StefanoFiumara** [NoScopeProductions/superawesomegame#1]

**Comment by fishywtf** [comment]
![img_20161017_201625](https://cloud.githubusercontent.com/assets/8198046/19461103/454f117c-94a7-11e6-9212-38d1be751ec2.jpg)
![img_20161017_201635](https://cloud.githubusercontent.com/assets/8198046/19461108/45549656-94a7-11e6-99c1-cba4ac18896f.jpg)
![img_20161017_201655](https://cloud.githubusercontent.com/assets/8198046/19461104/454f12f8-94a7-11e6-8e23-33db370e26ff.jpg)
![img_20161017_201708](https://cloud.githubusercontent.com/assets/8198046/19461106/4552b2dc-94a7-11e6-957e-4f6e96d21744.jpg)
![img_20161017_201717](https://cloud.githubusercontent.com/assets/8198046/19461107/4553933c-94a7-11e6-8dbb-7435aab56a6b.jpg)
![img_20161017_201723](https://cloud.githubusercontent.com/assets/8198046/19461105/4550cba2-94a7-11e6-82c9-b075ab90f0e0.jpg)

**Comment by xCmac** [comment]
Dude nice, I like them!

**Comment by StefanoFiumara** [comment]
Can we get these uploaded into the repository in a ConceptArt folder of some kind instead of them being tied to this issue?

Great work on this!
